-- ─────────────────────────────────────────────────────────────────────────────
-- Informes de Impacto (uno o varios por grupo; un mismo PDF puede repetirse
-- en varias filas cuando el informe sirve a varios grupos).
--
-- Ejecutar UNA VEZ en el SQL Editor de Supabase (junto con el RPC de abajo).
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.informe_impacto (
  id           bigint generated by default as identity primary key,
  grupo_id     integer not null references public.grupo(id),
  linea_id     integer references public.lineas(id),   -- opcional: informe de una línea específica
  titulo       text not null,
  fecha_inicio date not null,                          -- inicio de la evaluación de impacto
  fecha_fin    date,                                   -- presentación del informe (null = en curso)
  archivo_url  text,                                   -- PDF en el bucket informes_impacto
  created_at   timestamptz not null default now()
);

comment on table public.informe_impacto is
  'Informes de evaluación de impacto por grupo (módulo Catálogos + línea de tiempo de Proyectos)';

-- ─────────────────────────────────────────────────────────────────────────────
-- RPC de introspección del módulo Catálogos (scripts/catalogo_introspection.sql).
-- Nunca se ejecutó en esta BD y sin él el editor no puede descubrir las columnas
-- de una tabla vacía como informe_impacto. Es idempotente (create or replace).
-- ─────────────────────────────────────────────────────────────────────────────

create or replace function public.catalogo_columnas(p_tabla text)
returns table (
  column_name text,
  data_type   text,
  is_nullable boolean,
  is_pk       boolean,
  has_default boolean,
  ordinal     int
)
language sql
security definer
set search_path = public
as $$
  select
    c.column_name::text,
    c.data_type::text,
    (c.is_nullable = 'YES')                 as is_nullable,
    coalesce(pk.is_pk, false)               as is_pk,
    (c.column_default is not null or c.is_identity = 'YES') as has_default,
    c.ordinal_position::int                 as ordinal
  from information_schema.columns c
  left join (
    select kcu.column_name, true as is_pk
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on  kcu.constraint_name = tc.constraint_name
      and kcu.table_schema    = tc.table_schema
    where tc.constraint_type = 'PRIMARY KEY'
      and tc.table_schema    = 'public'
      and tc.table_name      = p_tabla
  ) pk on pk.column_name = c.column_name
  where c.table_schema = 'public'
    and c.table_name   = p_tabla
  order by c.ordinal_position;
$$;

grant execute on function public.catalogo_columnas(text) to service_role, authenticated;
