-- ─────────────────────────────────────────────────────────────────────────────
-- Saldos bancarios al cierre del ejercicio, POR BANCO (varios por año).
-- Reemplaza al rubro "Saldos en Bancos" de finanzas_anual como fuente del
-- widget de Inf. Gerencial. Se edita desde Catálogos.
--
-- Ejecutar UNA VEZ en el SQL Editor de Supabase.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.saldo_bancario (
  id         bigint generated by default as identity primary key,
  año        integer not null,
  banco      text not null,
  monto      numeric not null default 0,
  created_at timestamptz not null default now()
);

comment on table public.saldo_bancario is
  'Saldos bancarios al cierre del ejercicio, desglosados por banco (widget de Inf. Gerencial; edición en Catálogos)';

-- Siembra inicial: los saldos existentes en finanzas_anual (escenario Real)
-- entran como una fila "Consolidado" por año, para que el widget no quede
-- vacío. Al registrar el desglose real de un año, eliminar su "Consolidado".
-- Idempotente: solo siembra si la tabla está vacía.
insert into public.saldo_bancario (año, banco, monto)
select f.año, 'Consolidado', f.monto
from public.finanzas_anual f
where trim(f.rubro) = 'Saldos en Bancos'
  and f.escenario = 'Real'
  and not exists (select 1 from public.saldo_bancario);
