
-- Create table avance_proyecto
CREATE TABLE IF NOT EXISTS public.avance_proyecto (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id INTEGER NOT NULL REFERENCES public.proyectos(id),
    etapa_id INTEGER NOT NULL REFERENCES public.etapas(id),
    fecha DATE NOT NULL,
    sustento TEXT DEFAULT 'Cargado desde Base7',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.avance_proyecto ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON public.avance_proyecto
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for service role only" ON public.avance_proyecto
    FOR INSERT WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Enable update for service role only" ON public.avance_proyecto
    FOR UPDATE USING (auth.role() = 'service_role');

CREATE POLICY "Enable delete for service role only" ON public.avance_proyecto
    FOR DELETE USING (auth.role() = 'service_role');
